export enum AuthStep {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
  REQUIRES_2FA = 'REQUIRES_2FA',
  REQUIRES_VERIFICATION = 'REQUIRES_VERIFICATION',
  REQUIRES_PASSWORD_SETUP = 'REQUIRES_PASSWORD_SETUP',
  REQUIRES_ORG_SETUP = 'REQUIRES_ORG_SETUP',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}
